FROM nginx:alpine

# Copiar configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar archivos estáticos de la aplicación
COPY public /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]