version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./views:/var/www/views
      - ./routes:/var/www/routes
      - ./.env:/var/www/.env
      - ./helpers:/var/www/helpers
    depends_on:
      - db
    environment:
      DB_HOST: db
      MYSQL_DATABASE: login_app
      MYSQL_PASSWORD: root
      DB_CHARSET: utf8mb4

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
