version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./.env:/var/www/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-login
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
