services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./views:/var/www/html/views
      - ./routes:/var/www/html/routes
      - ./.env:/var/www/html/.env
      - ./helpers:/var/www/html/helpers
    expose:
      - "9000"
    depends_on:
      - db
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app

  db:
    image: postgres:17.5-alpine3.21
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env

volumes:
  db_data:
